### ISSUE TITLE
Not showing in "add integration" list

### ISSUE THREAD

**Issue by billybigbass** [tggm/rointe-hacs#1]
I've installed via HACS but when I go to configuration -> devices & services -> add integration Rointe Radiators HACS is not listed. Any idea what I've got wrong? Thanks.

**Comment by tggm** [comment]
@billybigbass Could you please check the Homeassistant log ? Especially after adding the integration in HACS?

**Comment by billybigbass** [comment]
Thanks for responding so quickly. Not sure what’s happened but after another server restart, after a nights sleep, I’ve noticed rointe hacs is showing up in the integration list. Sorry to have wasted your time. No warnings were showing in the logs at anytime.
