### ISSUE TITLE
Feature Request: Rointe Rome Series Water Heater

### ISSUE THREAD

**Issue by iiEviNii** [tggm/rointe-hacs#10]
Hi there! Thanks so much for putting this integration together.

Just looking to request support for the Rome Water Heaters also, which don't appear to currently be supported.

Thanks!

**Comment by selpas** [comment]
Hi

I have a Rointe Coralia Water Heater. I believe it's the same as Rome, but different name depending on country.

I went to /custom_components/rointe/const.py and just added the "acs" supported device, like this:
ROINTE_SUPPORTED_DEVICES = ["radiator", "towel", "therm", "radiatorb", "oval_towel", "acs"]

After restarting Hass the device is available and the integration seems to work correctly.

If this doesn't work you can enable logs, like mentioned in other issue in this integration, and check the correct device name

If the owner of integration can add this device "acs" to future versions, it will just work.

Thank you for the great integration @tggm !!

**Comment by iiEviNii** [comment]
Worked for me too! So it works for two different types of water heater.

Thanks for that!

**Comment by tggm** [comment]
ok, I'll add ACS but it will be experimental

**Comment by tggm** [comment]
Please try https://github.com/tggm/rointe-hacs/releases/tag/V1.5.1-b1

Requires enabling Beta versions for this repo under HACS
