### ISSUE TITLE
Rointe lite

### ISSUE THREAD

**Issue by cargen123** [tggm/rointe-hacs#2]
Would it be possible to connect to rointe lite instead of rointe connect?
I have an Olympia radiator and I use rointe lite instead.
Let me know if I can help in anyway.
Thanks

**Comment by tggm** [comment]
It might be. Does it work with https://www.rointeconnect.com/ ?

This integration was created based on the API calls identified on that webapp. Perhaps you could try and see if it works with Olympia radiators.

**Comment by cargen123** [comment]
Thanks tried with rointe connect and it is not working.
It doesn't recognize the radiator as compatible product

**Comment by tggm** [comment]
Rointe lite is not supported
