### ISSUE TITLE
Icon for integration

### ISSUE THREAD

**Issue by RealGandy** [tggm/rointe-hacs#3]
Any chance we can have an icon for the integration? Looks a bit bare without one.

On the Integrations configuration page all other integrations, core or custom, have icons.
![7F60D811-063F-4125-8289-4E752EE5F651](https://user-images.githubusercontent.com/305484/189470763-410fe1f9-e5a0-429b-a952-459417bcead5.jpeg)

thanks

**Comment by tggm** [comment]
Submitted a PR on rointe-hacs with the icons:

https://github.com/home-assistant/brands/pull/3647

**Comment by RealGandy** [comment]
Looks like that's been accepted and the icon now shows. 

Many Thanks
