### ISSUE TITLE
Fail devices when individual API calls fail

### ISSUE THREAD

**Issue by ShadowJonathan** [tggm/rointe-hacs#5]
Just quickly looking through the code, im seeing the following portion as an `else` statement for fetching individual device data:

https://github.com/tggm/rointe-hacs/blob/bf6dbf1c299a0c91c672bc9d58ada668524881d4/custom_components/rointe/device_manager.py#L110-L115

My suggestion would be to fail that device via `hass_available = False` when this block is hit?

**Comment by tggm** [comment]
Thanks @ShadowJonathan 

I'm in the process of cleaning up the code to submit it to the official homeassistant repo. I'll take this into account.

**Comment by ShadowJonathan** [comment]
Heya, I just saw the issue close, but I don't see code for it anywhere on the master branch or any other branch? Where are you doing development on this atm?

**Comment by tggm** [comment]
I'll make this correction here: https://github.com/tggm/core/tree/rointe-integration/homeassistant/components/rointe

My goal now is to prepare this integration to be submitted to home assistant's official repo. I won't be developing this HACS version anymore with new features.

**Comment by ShadowJonathan** [comment]
Understandable, I just wasn't sure where development did indeed happen, thank you for the link
