### ISSUE TITLE
Target temperature shown in HA doesn’t always match

### ISSUE THREAD

**Issue by RealGandy** [tggm/rointe-hacs#6]
I’ve noticed that when the scheduled temperature changes kick in, e.g. from Eco to Comfort, the radiator target temp shown in HA doesn’t update and remains the figure that was recorded at initialisation. 

thanks

**Comment by tcavin** [comment]
Hi,
Thx @tggm for your work on this integration 🙏 
I can also observe an issue 
When you use the scheduled mode (auto), with a eco target temperature of 18°C for instance, it's not reported in the climate card of HA (The climate device also reported a wrong temperature). It seems that the desired target temperature of the selected mode (eco, confort) is not correctly retrieved from Rointe to be shown in HA. 
But a previous manual temperature stays
Thx for your help if possible

**Comment by tcavin** [comment]
> Hi, Thx @tggm for your work on this integration 🙏 I can also observe an issue When you use the scheduled mode (auto), with a eco target temperature of 18°C for instance, it's not reported in the climate card of HA (The climate device also reported a wrong temperature). It seems that the desired target temperature of the selected mode (eco, confort) is not correctly retrieved from Rointe to be shown in HA. But a previous manual temperature stays Thx for your help if possible

I realize that maybe this issue is "normal" and connected to the upcoming features you're mentioning in home page ("Configure preset temperatures")...

**Comment by tggm** [comment]
On it.

**Comment by tggm** [comment]
@RealGandy Please try the beta version 1.5.0-b0. You'll need to go to HACS, then to the entry for this repo, update it and hit re-download. you should see an option to enable beta versions.

**Comment by RealGandy** [comment]
Tried with v1.5.1-b1.

The reported issue appears to be fixed, however a number of other sensors are no longer populated:

![IMG_2471](https://github.com/tggm/rointe-hacs/assets/305484/279a1491-7964-4eed-97c4-2c80a5901491)

Thanks

**Comment by tggm** [comment]
> Tried with v1.5.1-b1.
> 
> The reported issue appears to be fixed, however a number of other sensors are no longer populated:

Yeah, sorry about that. I synced the code to the version that's under review for main HA integration [on this PR](https://github.com/home-assistant/core/pull/83069).

Unfortunately, due to their rules 🤷‍♂️  they forced me to only submit a new integration with one platform only (in this case climate). All other platforms (sensors, update) have to be adder on a subsequent PR.

I'll try to re-add those sensors to the HACS version

**Comment by RealGandy** [comment]
Ok. If you can comment when they're back or make sure the release notes for the new HACS version that is to bring those sensors back. I've reverted to 1.4.x for now, as I've got some automation based on the current temp sensor.

**Comment by tggm** [comment]
Please try v1.6.0
