### ISSUE TITLE
Rointe Oval Wifi towel heater not supported?

### ISSUE THREAD

**Issue by brew-your-own** [tggm/rointe-hacs#7]
Hello,

I have 2 Oval wifi towel heaters from Rointe, and found your integration. This model seems to not be supported by the integration.
I would like to help add support - how do you test/debug the API calls to the rointe API ?

**Comment by tggm** [comment]
Hello!

You can try adding the following to your HA configuration.yaml

`logger:
  default: info
  logs:
    homeassistant.components.rointe: debug
    custom_components.hacs: debug
    custom_components.rointe: debug`

**Comment by tggm** [comment]
It's probably this:

`ROINTE_SUPPORTED_DEVICES = ["radiator", "towel", "therm", "radiatorb"]
`

**Comment by tggm** [comment]
Looking at the API's it's missing "oval_towel"

**Comment by tggm** [comment]
@brew-your-own I've made a quick update on HACS (v1.4.0) Please try it.

If any problems please enable logs and send them (as I don't have that device).

Thank you!

**Comment by tggm** [comment]
There are still some issues. I'll try to fix these in the next few days.

**Comment by tggm** [comment]
@brew-your-own please try version 1.4.3

**Comment by brew-your-own** [comment]
1.4.3 installed, it works :)
that was quick, thanks a lot.
